export enum actionType {
  LOGGING_IN = "LOGGING_IN",
  LOG_OUT = "LOG_OUT",
  LOGGING_IN_FAILED = "LOGGING_IN_FAILED",
  LOGGING_IN_SUCCESSFUL = "LOGGING_IN_SUCCESSFUL",
  REGISTERING_IN = "REGISTERING_IN",
  REGISTERING_IN_FAILED = "REGISTERING_IN_FAILED",
  REGISTERING_IN_SUCCESSFUL = "REGISTERING_IN_SUCCESSFUL",
  FETCHING_NEWS = "FETCHING_NEWS",
  FETCHED_NEWS_FAILED = "FETCHED_NEWS_FAILED",
  FETCHED_NEWS_SUCCESSFUL = "FETCHED_NEWS_SUCCESSFUL",
}
